### ISSUE TITLE
Add Antora Documentation and Add to Component Hub

### ISSUE THREAD

**Issue by Kidswiss** [vshn/cloudscale-metrics-collector#8]
### Description

Currently the documentation is just in the readme. Usually components are documented via Antora and collected centrally on https://hub.syn.tools/.

### Additional Context

-

### Logs

```shell
-
```

### Expected Behavior

The documentation is available under https://hub.syn.tools/

### Steps To Reproduce

-

### Versions

N/A

**Comment by davidgubler** [comment]
Taken care of with https://github.com/vshn/cloudscale-metrics-collector/pull/6/commits/69c26199df3177c71d085310a6be84ab221647a5

**Comment by Kidswiss** [comment]
That was fast :D
